[#25] 매장 Entity 구현
prgrms-be-devcourse/BE-03-BlackDogBucks pull request #34
Opened 2023-01-18 13:13 UTC by youngjijang

제목은`[#이슈번호] 이슈 제목` 으로 작성한다.   
- ex) [#8] 결제 기능

### 🍀 목적
- 매장 도메인 엔티티 구현

### 🌹 추가사항(있다면 적고 없다면 적지 않는다.)
- 매장 도메인 엔티티와 엔티티 테스트 코드 작성하였습니다.

❗️ 매장에 mapping된 사용자 권한 리스트는 아직 필드로 추가하지않았습니다. 구현되는대로 추가하도록 하겠습니다. 참고 부탁드려요.

#resolves

2023-01-18 13:49 UTC, tinajeong requested changes
깔끔한 코드 잘 보았습니다! 수정사항 반영부탁드립니다 :)

2023-01-18 13:49 UTC, tinajeong commented on src/test/java/com/prgrms/bdbks/domain/store/entity/StoreTest.java
> +	}
명확한 의도 설명 좋습니다!

2023-01-18 13:49 UTC, tinajeong commented on src/main/java/com/prgrms/bdbks/domain/store/entity/Store.java
> +	private String id;
자동생성로직이 아닌 상점코드 input 값을 그대로 사용하기 때문에 길이 명시가 필요해보입니다.

2023-01-18 13:49 UTC, tinajeong commented on .github/ISSUE_TEMPLATE/issue-template.md
> +### 완료조건
현재 pr과 무관한 md 파일이 포함되어 있습니다! 현재 upstream develop 브랜치에서 새로 만들어 Store 관련내용만 다시 올려주시면 approve 하겠습니다!

2023-01-18 14:24 UTC, youngjijang commented on .github/ISSUE_TEMPLATE/issue-template.md
> +### 완료조건
감사합니다~! main에서 딸려왔나봐요. 삭제하였습니다!

2023-01-18 14:44 UTC, devYSK requested changes

2023-01-18 14:44 UTC, devYSK commented on src/main/java/com/prgrms/bdbks/domain/store/entity/Store.java
> +
공간 데이터 타입을 이용해서 위도 경도와 연산을 하려면 BigDecinal로 위경도를 저장하는방법 보다  MySQL Spatial Type Point를 DB에 사용하면 좋을것 같습니다. 
 
 * https://momentjin.tistory.com/136
 * https://mvnrepository.com/artifact/org.locationtech.jts/jts-core
 * https://mvnrepository.com/artifact/org.hibernate/hibernate-spatial

2023-01-18 15:08 UTC, tinajeong commented on .github/ISSUE_TEMPLATE/issue-template.md
> +### 완료조건
pull_request_template.md 파일이 아직 남아있습니다! remove commit을 추가하시면 불필요한 커밋내역이 develop 브랜치에 포함되어서, 새로운 브랜치를 만들어 새로 PR을 올려주시면 승인하겠습니다

2023-01-18 15:10 UTC, tinajeong commented on src/main/java/com/prgrms/bdbks/domain/store/entity/Store.java
> +
오! 좋은 의견감사합니다.

2023-01-19 04:23 UTC, closed without merging

2023-01-19 04:24 UTC, youngjijang commented
잘못된 파일이 추가되어 PR close하고 재 PR 올릴예정입니다~