[#11, #12] 주문 접수, 주문 조회 API 구현
prgrms-be-devcourse/BE-03-BlackDogBucks pull request #68
Opened 2023-01-27 09:38 UTC by youngjijang

[#11 ] 주문 접수 API 구현
[#12 ] 주문 조회 API 구현

### 🍀 목적
- 주문 관련 API를 구현한다.

### 🌹 추가사항(있다면 적고 없다면 적지 않는다.)
- comflit 해결해였습니다~

### ❓ pr 포인트
- 코드 양이 많아 잘 부탁합니당 😭

2023-01-27 17:09 UTC, rlarltj approved these changes
안녕하세요 영수&영지님 
코드에서 정성이 많이 느껴지네요.
몇 자 남겼습니다. 주말 잘 보내세요 :-)

2023-01-27 17:09 UTC, rlarltj commented on src/main/java/com/prgrms/bdbks/domain/item/service/DefaultItemService.java
> +	@Transactional(readOnly = true)
제거하셔도 좋겠습니다!

2023-01-27 17:09 UTC, rlarltj commented on src/main/java/com/prgrms/bdbks/domain/order/entity/Order.java
> +	private OrderStatus orderStatus;
Entity에서 javax.validation은 제거해도 될 듯 합니다!!
OrderItem에도 동일합니다

2023-01-27 17:09 UTC, rlarltj commented on src/main/java/com/prgrms/bdbks/domain/order/service/OrderFacadeService.java
> +
알쓸신잡 공유합니다,,
Objects.isNull() 이녀석 내부에서  `coupon == null`로 동작하는것은 아실텐데요
API Note 보시면  `This method exists to be used as a java.util.function.Predicate, filter(Objects::isNull)`라
Null 체크 용도로 사용하는 것이 API 설계 목적과는 다르다네요. 보통  `coupon == null` 처럼 하나봐요

하지만 저도 즐겨씁니다. 그냥두셔도 돼요

2023-01-27 17:09 UTC, rlarltj commented on src/test/java/com/prgrms/bdbks/CustomDataJpaTest.java
> +@Import({P6spyConfiguration.class, JpaConfig.class})
테스트하는데 auditing이 안먹어서 생성일, 수정일 컬럼이 null로 박히더라고요.
저희는 해당 테스트 클래스에  `@Import JpaConfig.class`했는데, 여기 어노테이션에 추가해주셨네요
좋습니다 bbb

2023-01-27 17:09 UTC, rlarltj commented on src/test/resources/application-test.yml
> +    password: dudwl0804!
git ignore에 `application*.yml` 추가해주세요!
8월 4일 생일 미리 축하드립니다

2023-01-27 17:09 UTC, rlarltj commented on src/main/java/com/prgrms/bdbks/domain/order/dto/OrderCreateRequest.java
> +	@Size(min = 1, message = "주문할 아이템은 최소 {min} 다.니합야 여개")
요네로꾸거

2023-01-27 17:09 UTC, rlarltj commented on src/main/java/com/prgrms/bdbks/domain/order/entity/Order.java
> +	}
LGTM

2023-01-27 17:09 UTC, rlarltj commented on src/main/java/com/prgrms/bdbks/domain/order/entity/OrderItem.java
> +		}
LGTM

2023-01-27 17:09 UTC, rlarltj commented on src/main/java/com/prgrms/bdbks/domain/order/service/OrderFacadeService.java
> +	}
LGTM

2023-01-27 17:09 UTC, rlarltj commented on src/main/java/com/prgrms/bdbks/domain/payment/dto/OrderPayment.java
> +	}
이 DTO에서만 equals&hashCode를 오버라이딩 하셨더라고요.
이것이 언제 쓰이는지 궁금합니다!

2023-01-27 17:09 UTC, rlarltj commented on src/test/java/com/prgrms/bdbks/domain/card/entity/CardTest.java
> +		.birthDate(LocalDateTime.now().minusYears(10L).toLocalDate())
둘은 어떤 차이가 있나요 ?.!

2023-01-27 17:09 UTC, rlarltj commented on src/test/java/com/prgrms/bdbks/domain/order/entity/CustomOptionTest.java
> +
LGTM

2023-01-27 17:09 UTC, rlarltj commented on src/test/java/com/prgrms/bdbks/domain/order/repository/OrderSupportImplTest.java
> +	}
검증이 필요할 것 같습니다.

2023-01-27 17:09 UTC, rlarltj commented on src/test/java/com/prgrms/bdbks/domain/order/entity/OrderTest.java
> +}
LGTM

2023-01-27 17:52 UTC, geonwoo0215 requested changes
고생하셨습니다.

2023-01-27 17:52 UTC, geonwoo0215 commented on src/main/java/com/prgrms/bdbks/domain/item/api/ItemController.java
컨트롤러에 간단한 명세를 적어보는건 어떨까요?
```suggestion
```suggestion
/**
	 * <pre>
	 *     충전 카드 단건 조회
	 * </pre>
	 * @param user - 조회할 충전카드의 User
	 * @param cardId - 조회할 충전카드의 Id
	 * @return status : ok, body : CardSearchResponse
	 */
```
```

2023-01-27 17:52 UTC, geonwoo0215 commented on src/main/java/com/prgrms/bdbks/domain/order/dto/OrderCreateRequest.java
> +		@NotNull
몇 군데 error message 가 누락된 부분이 보여요.
message 작성이 필요해 보입니다.

2023-01-27 17:52 UTC, geonwoo0215 commented on src/main/java/com/prgrms/bdbks/domain/order/service/DefaultOrderService.java
> +	}
이 메서드는 왜 있는 건지 설명해 주실 수 있나요?

2023-01-27 17:52 UTC, geonwoo0215 commented on src/main/java/com/prgrms/bdbks/domain/order/service/DefaultOrderService.java
> +	private final OrderMapper orderMapper;
service 안에서 Mapper가 사용되지 않는 것처럼 보입니다.
삭제해도 되지 않을까요?

2023-01-28 06:39 UTC, devYSK commented on src/test/resources/application-test.yml
> +    password: dudwl0804!
@youngjijang

2023-01-28 06:39 UTC, devYSK commented on src/main/java/com/prgrms/bdbks/domain/payment/dto/OrderPayment.java
> +	}
@rlarltj 

테스트시 객체 비교에 쓰입니다. 일치하지 않아서 에러가 발생하더군요.

2023-01-28 06:40 UTC, devYSK commented on src/test/java/com/prgrms/bdbks/domain/order/repository/OrderSupportImplTest.java
> +	}
@rlarltj 

querydsl 쿼리 검증용인 테스트여서 쿼리만 의도한대로 나가는지 확인하는 테스트입니다!

2023-01-28 06:40 UTC, devYSK commented on src/main/java/com/prgrms/bdbks/domain/item/api/ItemController.java
반영하도록 하겠습니다.

2023-01-28 06:41 UTC, devYSK commented on src/main/java/com/prgrms/bdbks/domain/order/service/DefaultOrderService.java
> +	}
@geonwoo0215 

현재는 필요 없는 로직인거 같습니다. 지우도록 하겠습니다.

2023-01-28 09:14 UTC, youngjijang commented on src/main/java/com/prgrms/bdbks/domain/item/api/ItemController.java
수정했습니다!

2023-01-28 09:14 UTC, youngjijang commented on src/main/java/com/prgrms/bdbks/domain/item/service/DefaultItemService.java
> +	@Transactional(readOnly = true)
수정하였습니다!

2023-01-28 09:14 UTC, youngjijang commented on src/main/java/com/prgrms/bdbks/domain/order/dto/OrderCreateRequest.java
> +	@Size(min = 1, message = "주문할 아이템은 최소 {min} 다.니합야 여개")
다니합사감

2023-01-28 09:14 UTC, youngjijang commented on src/main/java/com/prgrms/bdbks/domain/order/dto/OrderCreateRequest.java
> +		@NotNull
추가하였습니다!

2023-01-28 09:14 UTC, youngjijang commented on src/main/java/com/prgrms/bdbks/domain/order/entity/Order.java
> +	private OrderStatus orderStatus;
변경하였습니다!

2023-01-28 09:14 UTC, youngjijang commented on src/main/java/com/prgrms/bdbks/domain/order/entity/Order.java
> +	}
👍🏻

2023-01-28 09:14 UTC, youngjijang commented on src/main/java/com/prgrms/bdbks/domain/order/entity/OrderItem.java
> +		}
👍🏻

2023-01-28 09:14 UTC, youngjijang commented on src/main/java/com/prgrms/bdbks/domain/order/service/DefaultOrderService.java
> +	private final OrderMapper orderMapper;
감사합니다~

2023-01-28 09:14 UTC, youngjijang commented on src/main/java/com/prgrms/bdbks/domain/order/service/DefaultOrderService.java
> +	}
수정하였습ㄴ니다~

2023-01-28 09:14 UTC, youngjijang commented on src/main/java/com/prgrms/bdbks/domain/order/service/OrderFacadeService.java
> +	}
👍🏻

2023-01-28 09:14 UTC, youngjijang commented on src/main/java/com/prgrms/bdbks/domain/order/service/OrderFacadeService.java
> +
그렇구뇨.. 보기에는 왠지 더 좋아보이는데 참고하겠습니다!

2023-01-28 09:14 UTC, youngjijang commented on src/main/java/com/prgrms/bdbks/domain/payment/dto/OrderPayment.java
> +	}
ㅋㅋㅋㅋㅋㅋㅋ

2023-01-28 09:14 UTC, youngjijang commented on src/main/java/com/prgrms/bdbks/domain/payment/dto/OrderPayment.java
> +	}
삭제하겠습니다!

2023-01-28 09:14 UTC, youngjijang commented on src/test/java/com/prgrms/bdbks/domain/card/entity/CardTest.java
> +		.birthDate(LocalDateTime.now().minusYears(10L).toLocalDate())
@devYSK

2023-01-28 09:14 UTC, youngjijang commented on src/test/java/com/prgrms/bdbks/domain/order/entity/CustomOptionTest.java
> +
👍🏻

2023-01-28 09:14 UTC, youngjijang commented on src/test/java/com/prgrms/bdbks/domain/order/entity/OrderTest.java
> +}
👍🏻

2023-01-28 09:14 UTC, youngjijang commented on src/test/resources/application-test.yml
> +    password: dudwl0804!
ㅋㅋㅋㅋㅋㅋㅋㅋㅋ이런..

2023-01-28 09:34 UTC, devYSK approved these changes
LGTM

2023-01-28 09:46 UTC, geonwoo0215 approved these changes

2023-01-28 09:48 UTC, merged