[#74] 사용자의 충전 카드를 등록, 단건 조회할 수 있다.
prgrms-be-devcourse/BE-03-BlackDogBucks pull request #75
Opened 2023-01-29 03:15 UTC by geonwoo0215

### 🍀 목적
- 카드 등록, 단건조회 기능 구현

### 🌹 추가사항
- 카드 등록, 단건조회 기능
- 카드 등록, 단건조회 기능 테스트

2023-01-29 08:35 UTC, devYSK requested changes
Good.

2023-01-29 08:35 UTC, devYSK commented on src/main/java/com/prgrms/bdbks/domain/card/api/CardController.java
> +		CardSaveResponse cardSaveResponse = cardService.create(user.getId(), cardSaveRequest);
`@Valid` 어노테이션이 빠져있습니다!

2023-01-29 08:35 UTC, devYSK commented on src/test/java/com/prgrms/bdbks/domain/card/api/CardControllerTest.java
> +		mockMvc.perform(post("/api/v1/cards")
BASE_REQUEST_URI 를 사용해도 될 것 같아요

2023-01-30 05:29 UTC, geonwoo0215 commented on src/main/java/com/prgrms/bdbks/domain/card/api/CardController.java
> +		CardSaveResponse cardSaveResponse = cardService.create(user.getId(), cardSaveRequest);
추가하였습니다.

2023-01-30 05:30 UTC, geonwoo0215 commented on src/test/java/com/prgrms/bdbks/domain/card/api/CardControllerTest.java
> +		mockMvc.perform(post("/api/v1/cards")
그러면 한군데에 관리할 수 있겠군요!
Couponcontroller도 같이 수정하였습니다.

2023-01-30 05:39 UTC, devYSK approved these changes

2023-01-30 05:39 UTC, merged