[#17, 18] 유저 권한 기능 추가
prgrms-be-devcourse/BE-03-BlackDogBucks pull request #95
Opened 2023-02-01 10:08 UTC by rlarltj

### 🍀 목적
- 유저의 권한 기능을 추가한다.

### 🌹 추가사항
- 메소드 별로 권한 지정
- 회원 가입 시 권한 자동 저장(ROLE_USER)

### ☕ 변경사항
- Service, Config class 리팩토링 

### ❓ pr 포인트
- 시큐리티 적용 했습니다. 컨트롤러 메소드와 컨트롤러 테스트 코드 변경 부탁드립니다!!
https://www.notion.so/backend-devcourse/Controller-Test-Security-f0471d19bd2a48c691ca5bf21c47399a

2023-02-02 04:35 UTC, devYSK requested changes

2023-02-02 04:35 UTC, devYSK commented on src/test/java/com/prgrms/bdbks/domain/user/repository/UserRepositoryTest.java
> +// import org.springframework.test.annotation.Rollback;
이 코드는 무엇이죠!? 사용하지 않는 코드는 지워주시거나 주석을 풀어주세요~

2023-02-02 04:35 UTC, devYSK commented on src/main/java/com/prgrms/bdbks/domain/user/service/DefaultUserService.java
> +	@Override
트랜잭션이 빠진것 같습니다. 

Authority는 보통 DB에 저장되어 값이 잘 바뀌지 않을것 같은데요. DB에서 찾아서 연관관계를 맺어주는것이 어떨까요

2023-02-02 04:35 UTC, devYSK commented on src/main/java/com/prgrms/bdbks/domain/user/jwt/CustomUserDetails.java
> +	public boolean isAccountNonExpired() {
각각의 메서드가 의미가 있어요.

모두 true보다 알맞는 도메인 로직을 구상해보는것은 어떨까요

2023-02-02 04:35 UTC, devYSK commented on src/main/java/com/prgrms/bdbks/domain/user/entity/UserAuthority.java
> +	public static UserAuthority create(User user, Authority authority) {
Authority를 주입해서 직접 UserAuthority를 만들어 연관관계를 맺는것,

UserAuthority를 주입해서 연관관계를 맺는것

저는 외부에서 UserAuthority를 주입하는것이 더 좋아보이는데요.
왜냐하면 비록 지금은 cascade가 있지 만, UserAUthority도 엔티티이고, 저장되어야 하니까요
둘 중에 어떤 방식이 나을지 고민해보면 좋을것같아요.

2023-02-02 04:35 UTC, devYSK commented on src/main/java/com/prgrms/bdbks/domain/user/api/UserController.java
> +	public ResponseEntity<String> changeUserAuthority(@Valid @RequestBody UserAuthChangeRequest userAuthChangeRequest) {
endpoint에서 자원의 식별자인 id륿 받지 않고 loginId를 바디로 받은 이유가 있나요?

2023-02-02 04:35 UTC, devYSK commented on src/main/java/com/prgrms/bdbks/config/security/SecurityConfig.java
> +			// .antMatchers("/**").authenticated()
사용하지 않는 주석은 지워주세요!

2023-02-02 06:56 UTC, rlarltj commented on src/main/java/com/prgrms/bdbks/domain/user/jwt/CustomUserDetails.java
> +	public boolean isAccountNonExpired() {
@devYSK 마지막 접속시간을 User 필드에 추가하고, 일정 시간 로그인하지 않으면 잠그는 것은 어떨까요?

2023-02-02 08:26 UTC, tinajeong commented on src/test/java/com/prgrms/bdbks/domain/user/repository/UserRepositoryTest.java
> +// import org.springframework.test.annotation.Rollback;
지웠습니다~

2023-02-02 09:19 UTC, devYSK commented on src/main/java/com/prgrms/bdbks/domain/user/jwt/CustomUserDetails.java
> +	public boolean isAccountNonExpired() {
@rlarltj 

좋은거같네요 휴면계정 여부도 알 수 있을거같아요?

2023-02-02 11:31 UTC, tinajeong commented on src/main/java/com/prgrms/bdbks/domain/user/jwt/CustomUserDetails.java
> +	public boolean isAccountNonExpired() {
@devYSK 네 휴면계정 여부도 알 수있게 처리했습니다~

2023-02-02 12:24 UTC, tinajeong commented on src/main/java/com/prgrms/bdbks/domain/user/api/UserController.java
> +	public ResponseEntity<String> changeUserAuthority(@Valid @RequestBody UserAuthChangeRequest userAuthChangeRequest) {
현재 로그인된 사용자의 정보는 Username이고, 
해당 값도 유니크하므로 클라이언트에서 요청하기 좋은 value라고 생각했습니다.

2023-02-02 12:53 UTC, tinajeong commented
@devYSK 리뷰 반영 완료했습니다! 재리뷰 부탁드려요

2023-02-03 04:09 UTC, devYSK approved these changes
LGTM

2023-02-03 04:09 UTC, devYSK commented on src/test/java/com/prgrms/bdbks/domain/user/service/DefaultUserServiceTest.java
>  		Optional<User> result = userService.findUser("notExistUser");
LGTM

2023-02-03 04:14 UTC, merged